# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 607003dd23a2a74092adfab50949c995bd83ccf715b5d9dc5f9632249a76c64c95ed937e7f60b5ad502c90db9fd14a92526e5fe0c8dad7ef7b7226513b9b6063

test:
  secret_key_base: e3901bfa8c8b323a8f3178726d608bc2ad99a1ab788543c5528a00a3afb8a560470449d8996a8b36ca8a667ccd174760c442180eb5099a2272e4c2154facdbda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
